[workspace]
members = ["crates/leyline", "crates/leyline-gfx", "crates/leyline-probe", "crates/leyline-pty", "crates/leyline-sound", "crates/leyline-text"]
exclude = ["third_party/vte"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
rust-version = "1.96"

[workspace.dependencies]
alacritty_terminal = { version = "0.25.1", default-features = false }
ash = { version = "0.38.0", default-features = false, features = ["loaded", "std"] }
gpu-allocator = { version = "0.28.0", default-features = false, features = ["std", "vulkan"] }
freetype-sys = { version = "0.23.0", features = ["bundled"] }
harfbuzz-sys = { version = "0.8.0", default-features = false, features = ["bundled"] }
smithay-client-toolkit = { version = "0.20.0", default-features = false, features = ["xkbcommon"] }
xkbcommon = "0.8.0"
wayland-client = { version = "0.31.14", features = ["system"] }
wayland-protocols = { version = "0.32.13", features = ["client", "staging", "unstable"] }
yeslogic-fontconfig-sys = { version = "6.0.1", features = ["dlopen"] }
clap = { version = "4.5.46", default-features = false, features = ["derive", "help", "std", "usage"] }
crossbeam-channel = "0.5.15"
serde = { version = "1.0.219", features = ["derive"] }
signal-hook = "0.3"
thiserror = "2.0.16"
toml = { version = "0.9.5", default-features = false, features = ["parse", "serde"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", default-features = false, features = ["ansi", "fmt", "registry"] }
unicode-bidi = "0.3.18"
unicode-segmentation = "1.12.0"
rustix = { version = "1.1.4", features = ["event", "fs", "system", "time"] }
regex-automata = "0.4.18"
libc = "0.2.175"
leyline-pty = { version = "0.1.0", path = "crates/leyline-pty" }
leyline-gfx = { version = "0.1.0", path = "crates/leyline-gfx" }
leyline-text = { version = "0.1.0", path = "crates/leyline-text" }
leyline-sound = { version = "0.1.0", path = "crates/leyline-sound" }
shaderc = "0.10.1"

[patch.crates-io]
vte = { path = "third_party/vte" }

[profile.release]
lto = "thin"
