[workspace]
members = ["crates/leyline", "crates/leyline-gfx", "crates/leyline-probe"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
rust-version = "1.96"

[workspace.dependencies]
alacritty_terminal = { version = "0.25.1", default-features = false }
ash = { version = "0.38.0", default-features = false, features = ["loaded", "std"] }
gpu-allocator = { version = "0.28.0", default-features = false, features = ["std", "vulkan"] }
freetype-sys = { version = "0.23.0", features = ["bundled"] }
harfbuzz-sys = { version = "0.8.0", default-features = false, features = ["bundled"] }
smithay-client-toolkit = { version = "0.20.0", default-features = false }
wayland-client = { version = "0.31.14", features = ["system"] }
wayland-protocols = { version = "0.32.13", features = ["client", "staging"] }
yeslogic-fontconfig-sys = { version = "6.0.1", features = ["dlopen"] }
clap = { version = "4.5.46", default-features = false, features = ["derive", "help", "std", "usage"] }
crossbeam-channel = "0.5.15"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.16"
toml = { version = "0.9.5", default-features = false, features = ["parse", "serde"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", default-features = false, features = ["ansi", "fmt", "registry"] }
rustix = { version = "1.1.4", features = ["event", "fs"] }
leyline-gfx = { version = "0.1.0", path = "crates/leyline-gfx" }
shaderc = "0.10.1"
