[package]
name = "leyline"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
leyline-gfx.workspace = true
leyline-pty.workspace = true
leyline-text.workspace = true
alacritty_terminal.workspace = true
clap.workspace = true
crossbeam-channel.workspace = true
serde.workspace = true
thiserror.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile = "3.21.0"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
